################ English language ##################
[en]
label = "English"
locale = "en-us"
contentDir = "content/english"
weight = 1

[vi]
label = "Tiếng Việt"
locale = "vi-vn"
contentDir = "content/vietnamese"
weight = 1
