############# Vietnamese navigation ##############

# main menu
[[main]]
name = "Trang chủ"
url = "/vi/"
weight = 1

[[main]]
name = "Giới thiệu"
url = "/vi/about"
weight = 2

[[main]]
name = "Danh sách BĐS"
url = "/vi/listings"
weight = 3

[[main]]
name = "Blog"
weight = 4

[[main]]
parent = "Blog"
name = "Tất cả bài đăng"
url = "/vi/blog/"
weight = 1

[[main]]
parent = "Blog"
name = "Tin tức Bất động sản"
url = "/vi/categories/real-estate/"
weight = 2

[[main]]
parent = "Blog"
name = "Mẹo nấu ăn"
url = "/vi/categories/cooking/"
weight = 3

[[main]]
name = "Liên hệ"
url = "/vi/contact"
weight = 5


# footer menu
[[footer]]
name = "Giới thiệu"
url = "/vi/about"
weight = 1

[[footer]]
name = "Danh sách BĐS"
url = "/vi/listings"
weight = 2

[[footer]]
name = "Tất cả bài đăng"
url = "/vi/blog"
weight = 3

[[footer]]
name = "Liên hệ"
url = "/vi/contact"
weight = 4
