############# Vietnamese navigation ##############

# main menu
[[main]]
name = "Trang chủ"
url = "/vi/"
weight = 1

[[main]]
name = "About"
url = "/vi/about"
weight = 2

[[main]]
name = "Elements"
url = "/vi/elements"
weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
url = "/vi/blog"

[[main]]
parent = "Pages"
name = "Liên hệ"
url = "/vi/contact"

[[main]]
parent = "Pages"
name = "Các tác giả"
url = "/vi/authors"

[[main]]
parent = "Pages"
name = "Danh mục"
url = "/vi/categories"

[[main]]
parent = "Pages"
name = "404 Page"
url = "/vi/404"

[[main]]
parent = "Pages"
name = "Danh sách BĐS"
url = "/vi/listings"

[[main]]
parent = "Pages"
name = "Agents"
url = "/vi/agents"


# footer menu
[[footer]]
name = "About"
url = "/vi/about"
weight = 1

[[footer]]
name = "Elements"
url = "/vi/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/vi/privacy-policy"
weight = 3
