############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Listings"
url = "/listings"
weight = 3

[[main]]
name = "Blog"
weight = 4

[[main]]
parent = "Blog"
name = "All Blog Posts"
url = "/blog/"
weight = 1

[[main]]
parent = "Blog"
name = "Real Estate News"
url = "/categories/real-estate/"
weight = 2

[[main]]
parent = "Blog"
name = "Cooking Tips"
url = "/categories/cooking/"
weight = 3

[[main]]
name = "Contact"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
