[build]
publish = "public"
command = "yarn project-setup; node scripts/themeGenerator.js; hugo --gc --minify --templateMetrics --templateMetricsHints --forceSyncStatic --baseURL https://thaogaeulhomes.netlify.app/"

[build.environment]
HUGO_VERSION = "0.158.0"
GO_VERSION = "1.25.1"
